### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by dipannita-g** [Shians/NanoMethViz#1]
Hi!

I am unable to install NanoMethViz. I get the following error:
```
Error: Failed to install 'NanoMethViz' from GitHub:
  (converted from warning) package ‘locfit’ is not available (for R version 3.4.4)
```
Any suggestions will be highly appreciated!

**Comment by PeteHaitch** [comment]
**NanoMethViz** is only available for R version 4.0 and above. Your error message indicates you are using R version 3.4.4. You will need to upgrade you version of R and then follow the installation instructions at http://www.bioconductor.org/packages/NanoMethViz/

@Shians Now that it's part of BioC, probably best to update the installation instructions to the official ones. Users installing from GitHub is ripe for errors like this.
