### ISSUE TITLE
nanopolish input format

### ISSUE THREAD

**Issue by yinshiyi** [Shians/NanoMethViz#21]
#########################
it seems the input is 
               sample   chr       pos strand statistic                              read_name

nanopolish has the output
chromosome	strand	start	end	read_name	log_lik_ratio	log_lik_methylated	log_lik_unmethylated	num_calling_strands	num_motifs	sequence
1	+	136533276	136533276	86bbfb92-5a22-44f7-aa58-e61d6ea3cd48	1.34	-165.98	-167.32	1	1	TGAGCCGTTTG
1	+	136533377	136533377	86bbfb92-5a22-44f7-aa58-e61d6ea3cd48	0.34	-214.55	-214.89	1	1	AGACTCGGGGA
1	+	136533400	136533400	86bbfb92-5a22-44f7-aa58-e61d6ea3cd48	-10.52	-251.71	-241.18	1	1	GAGGGCGATGG

this stat column is log_lik_ratio column?

Thank you

**Comment by Shians** [comment]
Hi there, it sounds like you are trying to use NanoMethViz directly with the output of Nanopolish. You need to import it into the NanoMethViz format first using `create_tabix_file()`.

**Comment by BeatrizFaustino** [comment]
how to transform nanopolish output to nanomethviz?
