### ISSUE TITLE
How to process Nanopore Remora output for DMR analysis?

### ISSUE THREAD

**Issue by kaanokay** [Shians/NanoMethViz#22]
Dear @Shians,

I'd like to thank you for developing this tool.

I have couple of questions about how to process Remora output for DMR analysis.

I have two groups: one of them is mutant, another one is control group. I used modbam2bed tool to get bedmethyl file from Remora bam files. I attached them in this post.

Could you help me how to find DMR regions between mutant and control groups using bed files through your R package? As I understand, your package supports Megalodon and Nanopolish but does not support Remora output. Btw, those groups are Mus musculus samples. I don't know what kind of input structure that I can produce as input for your package.

Best.

[control.txt](https://github.com/Shians/NanoMethViz/files/9936697/control.txt)
[mutant.txt](https://github.com/Shians/NanoMethViz/files/9936698/mutant.txt)

**Comment by Shians** [comment]
Than @kaanokay for the issue, modbams and bedmethyls don't currently work with NanoMethViz, which assume per-read data with coordinates and modification probabilities. This package currently outsources DMR detection to packages like edgeR, bsseq and DSS.

It's very useful to have the sample data, I think it can be converted into the format used in bsseq and DSS. Both those packages use bsseq objects, I'm not sure if they can import directly from bedmethyl, but it should be feasible and useful.

**Comment by kaanokay** [comment]
Hi @Shians,

Thank you so much for your reply. Its so helpful, I'll try analyze my data using bsseq.

Best.

**Comment by kaanokay** [comment]
Hi @Shians again,

I was wondering what input should be DMR analysis. It should be mod column/mod colum + canon column or;
mod colum/coverage column for methylation calculation? I'm not sure about it. Do you have thoughts on it?

Thanks!

**Comment by Shians** [comment]
I think that will depend on what DMR analysis tool you are using. For example [bsseq](https://bioconductor.org/packages/release/bioc/vignettes/bsseq/inst/doc/bsseq.html#3_Using_objects_of_class_BSseq) wants the following for their objects:


* genomic positions, including chromosome and location, for methylation loci.
* a (matrix) of M (Methylation) values, describing the number of read supporting methylation covering a single loci. Each row in this matrix is a methylation loci and each column is a sample.
* a (matrix) of Cov (Coverage) values, describing the total number of reads covering a single loci. Each row in this matrix is a methylation loci and each column is a sample.

**Comment by kaanokay** [comment]
Hi,

That's helpful. Thank you!

Bw.
