### ISSUE TITLE
Main spaghetti lines missing in my plot

### ISSUE THREAD

**Issue by YingziZhang-github** [Shians/NanoMethViz#27]
Hi Shian,

When I used `plot_region(nmeth_results, "chr*", $1, $2, spaghetti = TRUE)`, the output figure was missing the main spaghetti line of each group, as this:
![20051681977453_ pic](https://user-images.githubusercontent.com/28730426/233299394-abf0e95b-b074-4ad0-b06b-870263cb0465.jpg)

It was different than the example spaghetti figure:
![peg3_spaghetti](https://user-images.githubusercontent.com/28730426/233300199-c691124e-31a7-4fac-98ce-72b60e7f1784.png)

Would you suggest if I made anything wrong? Or did I miss to set any options?

Thank you! Looking forward to your reply!

Yingzi

**Comment by Shians** [comment]
Are there any warnings or errors that pop up? What does it look like if you set `spaghetti = FALSE`?

**Comment by YingziZhang-github** [comment]
Yes, there are warnings as the following:
```
Warning messages:
1: Computation failed in `stat_lowess()`
Caused by error in `as.data.frame.default()`:
! cannot coerce class ‘"lowess"’ to a data.frame
2: Removed 3 rows containing missing values (`geom_segment()`).
3: Removed 3 rows containing missing values (`geom_segment()`).
```

When I set `spaghetti = FALSE`, the warnings are as the same. The output figure turned out empty:
![Rplot01](https://user-images.githubusercontent.com/28730426/233313219-db9d3250-0f0c-42a0-beca-086b9e09366a.png)

**Comment by Shians** [comment]
That is very surprising, I really don't have any idea why it would happen. Does this happen for any other regions you try to plot?

**Comment by YingziZhang-github** [comment]
Hi Shian,

I tried three regions in different chromosomes. It happened the same way.

The warning message is
```
Computation failed in `stat_lowess()`
Caused by error in `as.data.frame.default()`:
! cannot coerce class '"lowess"' to a data.frame
```

The other NanoMethViz functions all run very well with my data, only the spaghetti plots behave weirdly as mentioned above. I may try to find other alternatives to make the line plot. Many thanks for the help.

Yingzi

**Comment by Shians** [comment]
If possible I would appreciate example data to reproduce this bug. If you could use `query_methy()` to extract an unimportant region where this bug occurs I could use that data to try and debug this issue.

**Comment by YingziZhang-github** [comment]
> example data to reproduce this bug

Hi Shian,

Thank you very much. I sent the example data to the email box su.s@wehi.edu.au.

Best,
Yingzi

**Comment by Shians** [comment]
I'm unable to reproduce the bug, but maybe I am using different settings to you. I suggest using the `heatmap = TRUE` argument which might provide further insight into what's going on.

```r
nmr <- NanoMethResult(
    methy = "experimental/smooth_bug.tsv.bgz",
    samples = samples
)

plot_region(nmr, "chr15", 24952550, 24953450, heatmap = TRUE, spaghetti = TRUE)
```

![smooth_bug](https://github.com/Shians/NanoMethViz/assets/6036662/235096e0-9291-4346-9654-b48d7a516e63)
