### ISSUE TITLE
DSS anda NanomethViz

### ISSUE THREAD

**Issue by BeatrizFaustino** [Shians/NanoMethViz#29]
Hello, I would like to know how to use the files generated by DSS, within the NanoMethViz function.

I would be grateful for the help!

**Comment by Shians** [comment]
Which particular file do you have in mind? Did you use DSS on Nanopore long read data or BS-Seq data?

**Comment by BeatrizFaustino** [comment]
Hello, thanks for the reply! I used DSS  for Nanopore long reads data. I have the callDMR.txt files as well as the nanopolish methylation calls! Can I view this data in NanoMethViz?

**Comment by Shians** [comment]
You may be able to use it to annotate regions using the `anno_regions` function in the `plot_genes()` function. It would be helpful if you could copy in the first few lines of callDMR.txt so I know what information it contains.

**Comment by BeatrizFaustino** [comment]
Thanks for the answer! Would I use the function for the callDMR.txt file generated by DSS?

The first two lines of the callDMR.txt file are:

chr start end length nCG meanMethy1 meanMethy2 diff.Methy areaStat
NC_071502.1 34119813 34120183 371 24 0.191503162830865 0.0102306134088378 0.181272549422028 68.4118706848033

Thank you very much in advance for the help

**Comment by Shians** [comment]
Sorry I forgot to get back to this. The table you described should be able to be put into the `anno_regions` argument when using `plot_gene()` or `plot_region()` functions. This will cause a section to be highlighted in the line graph of average methylation profiles.
