### ISSUE TITLE
NanoMethViz for bedmethyl files

### ISSUE THREAD

**Issue by kamungik** [Shians/NanoMethViz#31]
Hi, 
Does NanomethViz provide support for bedmethyl format files?

**Comment by Shians** [comment]
No sorry, because the main visualisations use per-read information and bedmethyl aggregates information at positions, NanoMethViz isn't quite suited for the format.

**Comment by selmapichot** [comment]
It would be great to have a function that handles bedmethyl format :)

**Comment by Shians** [comment]
The issue is that ModKit summarizes data at a different resolution that NanoMethViz requires, I can implement some of the plots but not with all the features, I will think a bit more about this.
